### ISSUE TITLE
Uncaught TypeError: Cannot match against 'undefined' or 'null'.

### ISSUE THREAD

**Issue by lexicalunit** [Stepsize/atom-better-git-blame#30]
1. Start Atom.
3. Open a git project and then any file in that project.
2. Run git blame command from the command palette.

This doesn't happen for all files and I don't know what makes it happen or not happen for specific files.

**Atom**: 1.26.0-beta0 x64
**Electron**: 1.7.11
**OS**: Mac OS X 10.13.4
**Thrown From**: [better-git-blame](https://github.com/Stepsize/atom-better-git-blame) package 0.4.3

### Stack Trace

Uncaught TypeError: Cannot match against 'undefined' or 'null'.

```
At /Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:3578

TypeError: Cannot match against 'undefined' or 'null'.
    at TextEditor.indentLevelForLine (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:3578:38)
    at TextEditor.indentationForBufferRow (/Applications/Atom Beta.app/Contents/Resources/app/src/text-editor.js:3529:23)
    at CodeSelector.getFoldEnds (/packages/better-git-blame/dist/bundle.js:28688:32)
    at CodeSelector.calculateCodeFolds (/packages/better-git-blame/dist/bundle.js:28669:14)
    at /packages/better-git-blame/dist/bundle.js:28665:14)
    at /packages/better-git-blame/dist/bundle.js:28740:29)
    at toggleGutterView (/packages/better-git-blame/dist/bundle.js:28997:33)
    at /packages/better-git-blame/dist/bundle.js:28959:42)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:384:49)
    at Object.didConfirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/lib/command-palette-view.js:152:35)
    at SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:401:26)
    at HTMLDivElement.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/command-palette/node_modules/atom-select-list/src/select-list-view.js:106:20)
    at CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/command-registry.js:384:49)
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:621:22)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:412:28)
    at WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app/src/window-event-handler.js:110:40)
```

### Commands

```
     -2:13.1.0 fuzzy-finder:toggle-file-finder (div.tool-panel.tree-view)
     -2:11.5.0 core:move-down (input.hidden-input)
     -2:11.2.0 core:confirm (input.hidden-input)
     -1:53.4.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
  3x -1:51.1.0 core:move-down (input.hidden-input)
     -1:50.4.0 core:confirm (input.hidden-input)
 10x -0:18.3.0 core:cut (input.hidden-input)
     -0:17.4.0 core:undo (input.hidden-input)
     -0:13.8.0 pane:show-next-item (input.hidden-input)
     -0:11.4.0 command-palette:toggle (input.hidden-input)
     -0:10 core:confirm (input.hidden-input)
     -0:10 better-git-blame:toggle (input.hidden-input)
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
aesthetic-ui 4.0.0 
atom-beautify 0.32.2 
atom-isort 2.6.1 
atom-language-avro 0.0.13 
atom-notes 1.16.3 
auto-update-packages 1.0.1 
autocomplete-python 1.10.5 
base16-syntax 1.8.1 
better-git-blame 0.4.3 
busy-signal 1.4.3 
column-select 1.0.1 
cursor-indicator 1.3.0 
docblockr 0.13.7 
event-watch 4.1.5 
file-icons 2.1.18 
flatwhite-syntax 0.8.1 
force-tab 0.2.4 
format-shell 2.0.0 
highlight-selected 0.13.1 
indent-guide-improved 1.4.13 
intentions 1.1.5 
isotope-light-ui 2.3.0 
isotope-ui 2.8.5 
language-applescript 0.3.0 
language-atom-notes 0.2.3 
language-babel 2.84.0 
language-cmake 1.1.0 
language-diff 0.7.0 
language-docker 1.1.8 
language-groovy 0.7.0 
language-latex 1.1.1 
language-protobuf 0.7.1 
language-restructuredtext 1.1.0 
language-rust 0.4.12 
language-scala 1.1.9 
line-length-break 0.4.0 
linter 2.2.0 
linter-clang 4.1.2 
linter-coffeelint 1.3.1 
linter-csslint 2.0.0 
linter-docker 0.3.0 
linter-erb 1.1.0 
linter-eslint 8.4.1 
linter-flake8 2.3.0 
linter-jsonlint 1.3.0 
linter-rubocop 2.2.3 
linter-shellcheck 1.4.6 
linter-tidy 2.3.1 
linter-ui-default 1.7.1 
linter-write-good 0.9.0 
minimap 4.29.8 
minimap-find-and-replace 4.5.2 
minimap-git-diff 4.3.1 
minimap-highlight-selected 4.6.1 
minimap-selection 4.5.0 
multi-wrap-guide 1.1.5 
native-ui 0.25.2 
no-title-bar 1.11.4 
pretty-json 2.0.0 
python-yapf 0.14.0 
red-wavy-underline 0.3.3 
ruby-block 0.3.6 
set-syntax 0.4.0 
soft-wrap-indicator 1.1.0 
sort-lines 0.18.0 
standard-formatter 2.8.0 
Stylus 3.1.1 
tab-control 0.6.10 
tabs-to-spaces 1.0.3 
tinacious-design-syntax-purple 0.5.1 
toggle-quotes 1.1.0 
trailing-spaces 0.4.0 
unity-ui 2.1.11 
```

**Comment by nomeyer** [comment]
Hi @lexicalunit, thanks for reporting this. We've released `0.4.4` which should prevent this from happening.

I wasn't able to reproduce the problem but I added a safety check so that at least the package doesn't crash.

✌️
