### ISSUE TITLE
Uncaught Error: Tried to create a gutter with a name that is already in use.

### ISSUE THREAD

**Issue by dcchambers** [Stepsize/atom-better-git-blame#44]
[Enter steps to reproduce:]

1. Open up a fresh copy of a project
2. Press Ctrl+B to open up Git Blame panel
3. This error is thrown

**Atom**: 1.38.2 x64
**Electron**: 2.0.18
**OS**: Mac OS X 10.14.4
**Thrown From**: [better-git-blame](https://github.com/Stepsize/atom-better-git-blame) package 0.4.7

### Stack Trace

Uncaught Error: Tried to create a gutter with a name that is already in use.

```
At /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11

Error: Tried to create a gutter with a name that is already in use.
    at GutterContainer.addGutter (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:562535)
    at TextEditor.addGutter (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:49406)
    at /packages/better-git-blame/dist/bundle.js:28756:35)
    at toggleGutterView (/packages/better-git-blame/dist/bundle.js:29015:33)
    at /packages/better-git-blame/dist/bundle.js:28977:42)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:348418)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:346893)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:717210)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:725133)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
  2x -0:18.3.0 better-git-blame:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-inline-blame 0.0.6 
autocomplete-emojis 2.5.0 
better-git-blame 0.4.7 
busy-signal 2.0.1 
intentions 1.1.5 
language-docker 1.1.8 
linter 2.3.0 
linter-ui-default 1.7.1 
monokai 0.24.0 
monokai-old-school 3.0.0 
monokai-sublime 1.0.0 
pdf-view 0.71.0 
terminal-tab 0.5.7 
thesaurus 0.3.0 
```

**Comment by dcchambers** [comment]
The error persists after restarting Atom as well.
